#spring:
#  datasource:
#    url: jdbc:mysql://172.16.23.210:3306/sfcity_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: sfcity
#    password: gX0yA1nP1qS3
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/task_flow
