apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-flow-api
  labels:
    app: task-flow-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-flow-api
  template:
    metadata:
      labels:
        app: task-flow-api
    spec:
      containers:
        - name: task-flow-api
          image: your-docker-username/task_flow_api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
